### ISSUE TITLE
Can't install google-cloud-pubsub on RPI

### ISSUE THREAD

**Issue by dodgyrabbit** [ARM-software/Cloud-IoT-Core-Kit-Examples#4]
Trying to follow readme instructions and got stuck on this step.
`pip install --upgrade google-cloud-pubsub`

Note this is running on my RPI. I've updated the firmware and other packages as per the readme.

It fails with an install error that I need help resolving.
Something similar mentioned [here](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4186) but I don't know how to proceed.

pi@raspberrypi:~/iot/Cloud-IoT-Core-Kit-Examples/CPUTemp $ pip install --upgrade google-cloud-pubsub
Downloading/unpacking google-cloud-pubsub
  Downloading google_cloud_pubsub-0.28.4-py2.py3-none-any.whl (79kB): 79kB downloaded
Downloading/unpacking grpc-google-iam-v1<0.12dev,>=0.11.1 (from google-cloud-pubsub)
  Downloading grpc-google-iam-v1-0.11.4.tar.gz
  Running setup.py (path:/tmp/pip-build-eqe101m8/grpc-google-iam-v1/setup.py) egg_info for package grpc-google-iam-v1
Downloading/unpacking google-gax<0.16dev,>=0.15.13 (from google-cloud-pubsub)
  Downloading google-gax-0.15.15.tar.gz (109kB): 109kB downloaded
  Running setup.py (path:/tmp/pip-build-eqe101m8/google-gax/setup.py) egg_info for package google-gax
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Downloading/unpacking psutil<6.0dev,>=5.2.2 (from google-cloud-pubsub)
  Downloading psutil-5.4.0.tar.gz (406kB): 406kB downloaded
  Running setup.py (path:/tmp/pip-build-eqe101m8/psutil/setup.py) egg_info for package psutil
Downloading/unpacking google-cloud-core[grpc]<0.28dev,>=0.27.1 (from google-cloud-pubsub)
  Downloading google_cloud_core-0.27.1-py2.py3-none-any.whl (50kB): 50kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2680, in requires
    deps.extend(dm[safe_extra(ext)])
KeyError: 'grpc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2683, in requires
    "%s has no such extra feature %r" % (self, ext)
**pkg_resources.UnknownExtra: google-cloud-core 0.27.1 has no such extra feature 'grpc'**

Storing debug log for failure in /home/pi/.pip/pip.log

**Comment by mdupuy** [comment]
Ah, google-cloud-pubsub depends on google-cloud-core now.

I've updated the documentation to read:

sudo -s
apt install build-essential libssl-dev libffi-dev python-dev
pip install pyjwt paho-mqtt cryptography
pip install --upgrade google-api-python-client
**pip install --upgrade google-cloud-core**
pip install --upgrade google-cloud-pubsub
exit

Let me know if that works for you. Thanks for reporting this!

**Comment by dodgyrabbit** [comment]
This worked thanks but I ran into some more trouble.
If I recall, it complained about cffi library. So I did this and it worked:
sudo pip -vvv install --upgrade --force-reinstall cffi
